language: python

sudo: yes

matrix:
 include:
  - python: 2.7
    dist: bionic
    env: NUMPY_VERSION=">=1.6.0,<1.7.0"
  - python: 2.7
    dist: bionic
    env: NUMPY_VERSION=">=1.16.0,<1.17.0"
  - python: 3.5
    dist: xenial
    env: NUMPY_VERSION=">=1.10.0,<1.11.0"
  - python: 3.5
    dist: xenial
    env: NUMPY_VERSION=">=1.18.0,<1.19.0"
  - python: 3.6
    dist: bionic
    env: NUMPY_VERSION=">=1.12.0,<1.13.0"
  - python: 3.6
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0"
  - python: 3.7
    dist: bionic
    env: NUMPY_VERSION=">=1.15.1,<1.16.0"
  - python: 3.7
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0"
  - python: 3.8
    dist: bionic
    env: NUMPY_VERSION=">=1.17.0,<1.18.0"
  - python: 3.8
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libhdf5-serial-dev gcc gfortran xvfb

install:
 - pip install --force-reinstall "numpy${NUMPY_VERSION}"
 - pip install scipy
 - pip install "matplotlib<3.3"
 - pip install h5py
 - pip install networkx
 - pip install ffnet
 - pip freeze #summarize what we have for debug purposes
 - wget https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_1/linux/cdf37_1-dist-cdf.tar.gz; tar xzf cdf37_1-dist-cdf.tar.gz; cd cdf37_1-dist; make OS=linux ENV=gnu all; make INSTALLDIR=$HOME install; cd ..

script:
 - python setup.py install
 - cd tests; . /home/travis/bin/definitions.B; xvfb-run python test_all.py -v

notifications:
 webhooks: https://www.travisbuddy.com/
 on_success: never
