language: python

sudo: yes

matrix:
 include:
# For the most part, these versions are: what's the earliest we support,
# coupled with what's the earliest and latest version of each dep
# which works with that Python. (For latest, generally specify no version
# and let pip select latest, unless there's a max version known to work
# with a given Python.)
# Old astropy + new gcc requires overriding some CFLAGS, see
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871156
  - python: 2.7
    dist: bionic
    env: NUMPY_VERSION=">=1.10.0,<1.11.0" PIPLIST="scipy>=0.11.0,<0.12.0 matplotlib>=1.5.0,<1.6.0 networkx>=1.0,<1.1 h5py>=2.6,<2.7 ffnet>=0.7.0,<0.8 astropy>=1.0,<1.1" CFLAGS="-Wno-error=format-security"
  - python: 2.7
    dist: bionic
    env: NUMPY_VERSION=">=1.16.0,<1.17.0" PIPLIST="scipy matplotlib networkx h5py ffnet astropy"
  - python: 3.5
    dist: xenial
    env: NUMPY_VERSION=">=1.10.0,<1.11.0" PIPLIST="scipy>=0.17.0,<0.18.0 matplotlib>=1.5.0,<1.6.0 networkx>=1.3,<1.4 h5py>=2.6,<2.7 ffnet>=0.8.0<0.9 astropy>=1.0,<1.1"
  - python: 3.5
    dist: xenial
    env: NUMPY_VERSION=">=1.18.0,<1.19.0" PIPLIST="scipy matplotlib networkx h5py ffnet astropy"
  - python: 3.6
    dist: bionic
    env: NUMPY_VERSION=">=1.12.0,<1.13.0" PIPLIST="scipy>=0.19.0,<0.20.0 matplotlib>=1.5.0,<1.6.0 networkx>=1.3,<1.4 h5py>=2.6,<2.7 ffnet>=0.8.0<0.9 astropy>=1.0,<1.1" CFLAGS="-Wno-error=format-security"
  - python: 3.6
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0" PIPLIST="scipy matplotlib networkx h5py ffnet astropy"
  - python: 3.7
    dist: bionic
    env: NUMPY_VERSION=">=1.15.1,<1.16.0" PIPLIST="scipy>=1.0.0,<1.1.0 matplotlib>=1.5.0,<1.6.0 networkx>=1.3,<1.4 h5py>=2.6,<2.7 ffnet>=0.8.0<0.9 astropy>=2.0,<2.1" CFLAGS="-Wno-error=format-security"
  - python: 3.7
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0" PIPLIST="scipy matplotlib networkx h5py ffnet astropy"
  - python: 3.8
    dist: bionic
    env: NUMPY_VERSION=">=1.17.0,<1.18.0" PIPLIST="scipy>=1.0.0,<1.1.0 matplotlib>=1.5.0,<1.6.0 networkx>=1.3,<1.4 h5py>=2.6,<2.7 ffnet>=0.8.0<0.9 astropy>=2.0,<2.1" CFLAGS="-Wno-error=format-security"
  - python: 3.8
    dist: bionic
    env: NUMPY_VERSION=">=1.18.0" PIPLIST="scipy matplotlib networkx h5py ffnet astropy"

before_install:
 - sudo apt-get update -qq
 # blas/lapack dev needed for scipy versions without binary wheels
 - sudo apt-get install libhdf5-serial-dev gcc gfortran xvfb libblas-dev liblapack-dev

install:
 - pip install --force-reinstall "numpy${NUMPY_VERSION}"
 # Make sure new packages don't override numpy version
 - pip install "numpy${NUMPY_VERSION}" ${PIPLIST}
 - pip freeze #summarize what we have for debug purposes
 - wget https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_1/linux/cdf37_1-dist-cdf.tar.gz; tar xzf cdf37_1-dist-cdf.tar.gz; cd cdf37_1-dist; make OS=linux ENV=gnu all; make INSTALLDIR=$HOME install; cd ..

script:
 - python setup.py install
 - cd tests; . /home/travis/bin/definitions.B; xvfb-run python test_all.py -v

notifications:
 webhooks: https://www.travisbuddy.com/
 on_success: never
