language: python

matrix:
 include:
  - python: 2.7
    env: NUMPY_VERSION="==1.15.4"
  - python: 2.7
    env: NUMPY_VERSION="==1.13.3"
  - python: 2.7
    env: NUMPY_VERSION="==1.11.3"
  - python: 3.5
    env: NUMPY_VERSION=">=1.6,!=1.15.0"
  - python: 3.5
    env: NUMPY_VERSION="==1.13.3"
  - python: 3.6
    env: NUMPY_VERSION=">=1.6,!=1.15.0"
  - python: 3.6
    env: NUMPY_VERSION="==1.13.3"
  - python: 3.7
    dist: xenial
    sudo: yes
    env: NUMPY_VERSION=">=1.6,!=1.15.0"
  - python: 3.7
    dist: xenial
    env: NUMPY_VERSION="==1.14.5"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libhdf5-serial-dev gcc gfortran xvfb

install:
 - pip install --force-reinstall "numpy${NUMPY_VERSION}"
 - pip install scipy
 - pip install matplotlib
 - pip install h5py
 - pip install networkx
 - pip install ffnet
 - pip freeze #summarize what we have for debug purposes
 - wget https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_1/linux/cdf37_1-dist-cdf.tar.gz; tar xzf cdf37_1-dist-cdf.tar.gz; cd cdf37_1-dist; make OS=linux ENV=gnu all; make INSTALLDIR=$HOME install; cd ..

script:
 - python setup.py install
 - cd tests; . /home/travis/bin/definitions.B; xvfb-run python test_all.py

notifications:
 webhooks: https://www.travisbuddy.com/
 on_success: never
