language: python

matrix:
 include:
  - python: 2.7
    env: NUMPY_VERSION="==1.15.2"
  - python: 2.7
    env: NUMPY_VERSION="==1.13.3"
  - python: 2.7
    env: NUMPY_VERSION="==1.11.3"
  - python: 3.5
    env: NUMPY_VERSION=">=1.6,!=1.15.0"
  - python: 3.5
    env: NUMPY_VERSION="==1.13.3"
  - python: 3.6
    env: NUMPY_VERSION=">=1.6,!=1.15.0"
  - python: 3.6
    env: NUMPY_VERSION="==1.13.3"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libhdf5-serial-dev gcc gfortran

install:
 - pip install --force-reinstall "numpy${NUMPY_VERSION}"
 - pip install scipy
 - pip install matplotlib
 - pip install h5py
 - pip install networkx
 - pip install ffnet
 - wget https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_0/linux/cdf37_0-dist-cdf.tar.gz; tar xzf cdf37_0-dist-cdf.tar.gz; cd cdf37_0-dist; make OS=linux ENV=gnu all; make INSTALLDIR=$HOME install; cd ..

before_script:
 - "export DISPLAY=:99.0" #Travis has no X11, so we dummy this here to allow our graphical tests to run
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
 - python setup.py install
 - cd tests; . /home/travis/bin/definitions.B; python test_spacepy.py

notifications:
 webhooks: https://www.travisbuddy.com/
 on_success: never
